// resources/js/Pages/Auth/Login.vue
<template>
    <div class="login-wrapper">
        <div class="login-card">
            <div class="login-header">
                <i class="bi bi-grid-3x3-gap-fill"></i>
                <h2>سیستم بازدید تجهیزات</h2>
                <p>شرکت توزیع نیروی برق استان یزد</p>
            </div>
            
            <div class="login-body">
                <div v-if="status" class="alert alert-success">
                    {{ status }}
                </div>
                
                <div v-if="Object.keys(errors).length > 0" class="alert alert-danger">
                    اطلاعات وارد شده صحیح نمی‌باشد.
                </div>
                
                <form @submit.prevent="submit">
                    <div class="form-group">
                        <label>ایمیل</label>
                        <input type="email" v-model="form.email" class="form-control" placeholder="admin@example.com" autofocus>
                        <div v-if="form.errors.email" class="error-text">{{ form.errors.email }}</div>
                    </div>
                    
                    <div class="form-group">
                        <label>رمز عبور</label>
                        <input type="password" v-model="form.password" class="form-control" placeholder="********">
                        <div v-if="form.errors.password" class="error-text">{{ form.errors.password }}</div>
                    </div>
                    
                    <div class="form-group">
                        <label class="checkbox">
                            <input type="checkbox" v-model="form.remember">
                            <span>مرا به خاطر بسپار</span>
                        </label>
                    </div>
                    
                    <button type="submit" class="btn-login" :disabled="form.processing">
                        {{ form.processing ? 'در حال ورود...' : 'ورود به سیستم' }}
                    </button>
                    
                    <div class="form-footer" v-if="canResetPassword">
                        <a :href="route('password.request')">رمز عبور را فراموش کرده‌اید؟</a>
                    </div>
                </form>
            </div>
        </div>
        
        <div class="company-info">
            شرکت توزیع نیروی برق استان یزد | نسخه 2.0
        </div>
    </div>
</template>

<script>
import { useForm } from '@inertiajs/inertia-vue3';

export default {
    props: {
        canResetPassword: Boolean,
        status: String,
        errors: Object
    },
    setup() {
        const form = useForm({
            email: '',
            password: '',
            remember: false,
        });

        function submit() {
            form.post(route('login'), {
                onFinish: () => form.reset('password'),
            });
        }

        return { form, submit };
    }
};
</script>

<style scoped>
* {
    font-family: 'Vazirmatn', sans-serif;
}

.login-wrapper {
    min-height: 100vh;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    padding: 20px;
}

.login-card {
    background: white;
    border-radius: 24px;
    box-shadow: 0 20px 40px rgba(0,0,0,0.2);
    width: 100%;
    max-width: 420px;
    overflow: hidden;
}

.login-header {
    background: linear-gradient(135deg, #2c3e50, #1e2b37);
    padding: 40px 30px;
    text-align: center;
    color: white;
}

.login-header i {
    font-size: 50px;
    color: #3498db;
    margin-bottom: 15px;
}

.login-header h2 {
    font-size: 1.5rem;
    margin-bottom: 5px;
}

.login-header p {
    font-size: 0.8rem;
    opacity: 0.8;
}

.login-body {
    padding: 35px 30px;
}

.form-group {
    margin-bottom: 20px;
}

.form-group label {
    display: block;
    font-weight: 600;
    color: #333;
    margin-bottom: 8px;
}

.form-control {
    width: 100%;
    padding: 12px 15px;
    border: 2px solid #e9ecef;
    border-radius: 12px;
    font-size: 0.95rem;
    transition: all 0.3s;
}

.form-control:focus {
    border-color: #3498db;
    outline: none;
}

.checkbox {
    display: flex;
    align-items: center;
    gap: 8px;
    cursor: pointer;
    font-weight: normal;
}

.btn-login {
    width: 100%;
    padding: 12px;
    background: linear-gradient(135deg, #3498db, #2980b9);
    border: none;
    border-radius: 12px;
    color: white;
    font-size: 1rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s;
}

.btn-login:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 5px 15px rgba(52,152,219,0.4);
}

.btn-login:disabled {
    opacity: 0.7;
    cursor: not-allowed;
}

.form-footer {
    text-align: center;
    margin-top: 20px;
    padding-top: 15px;
    border-top: 1px solid #e9ecef;
}

.form-footer a {
    color: #3498db;
    text-decoration: none;
    font-size: 0.85rem;
}

.alert {
    padding: 12px;
    border-radius: 12px;
    margin-bottom: 20px;
    text-align: center;
}

.alert-success {
    background: #d4edda;
    color: #28a745;
}

.alert-danger {
    background: #fee2e2;
    color: #dc3545;
}

.error-text {
    color: #dc3545;
    font-size: 0.75rem;
    margin-top: 5px;
}

.company-info {
    text-align: center;
    margin-top: 20px;
    color: rgba(255,255,255,0.7);
    font-size: 0.75rem;
}
</style>

// resources/js/Pages/Auth/Login.jsx
import React, { useState } from 'react';
import { useForm, Link } from '@inertiajs/inertia-react';

export default function Login({ status, canResetPassword, errors }) {
    const { data, setData, post, processing } = useForm({
        email: '',
        password: '',
        remember: false,
    });

    const submit = (e) => {
        e.preventDefault();
        post(route('login'));
    };

    return (
        <div className="login-wrapper">
            {/* RTU و کنترلرها */}
            <div className="bg-emoji-1">🎛️</div>
            <div className="bg-emoji-2">🕹️</div>
            <div className="bg-emoji-3">📟</div>
            <div className="bg-emoji-4">💻</div>
            <div className="bg-emoji-5">🖥️</div>
            
            {/* مودم و ارتباطات بیسیم */}
            <div className="bg-emoji-6">📡</div>
            <div className="bg-emoji-7">📶</div>
            <div className="bg-emoji-8">📱</div>
            <div className="bg-emoji-9">🌐</div>
            <div className="bg-emoji-10">🔄</div>
            <div className="bg-emoji-11">📞</div>
            
            {/* تابلو برق و تجهیزات */}
            <div className="bg-emoji-16">⚡</div>
            <div className="bg-emoji-17">🔌</div>
            <div className="bg-emoji-18">🔋</div>
            <div className="bg-emoji-19">💡</div>
            <div className="bg-emoji-20">🔧</div>
            <div className="bg-emoji-21">⚙️</div>
            
            {/* مانیتورینگ و نمایشگر */}
            <div className="bg-emoji-22">📺</div>
            <div className="bg-emoji-23">📊</div>
            <div className="bg-emoji-24">📈</div>
            <div className="bg-emoji-25">🎯</div>
            
            {/* امنیت */}
            <div className="bg-emoji-26">🔒</div>
            <div className="bg-emoji-27">🛡️</div>
            
            {/* سیم کارت */}
            <div className="bg-emoji-29">📇</div>
            <div className="bg-emoji-30">📲</div>
            
            {/* تنظیمات */}
            <div className="bg-emoji-31">🎚️</div>
            <div className="bg-emoji-32">⏱️</div>
            <div className="bg-emoji-33">🗝️</div>
            <div className="bg-emoji-34">📳</div>
            
            <div className="login-card">
                <div className="login-left">
                    <div className="login-header">
                        <div className="logo-icon">
                            <i className="bi bi-grid-3x3-gap-fill"></i>
                        </div>
                        <h2>سیستم بازدید تجهیزات</h2>
                        <p>شرکت توزیع نیروی برق استان یزد</p>
                    </div>
                    
                    {status && (
                        <div className="alert alert-success">{status}</div>
                    )}
                    
                    {Object.keys(errors).length > 0 && (
                        <div className="alert alert-danger">
                            اطلاعات وارد شده صحیح نمی‌باشد.
                        </div>
                    )}
                    
                    <form onSubmit={submit}>
                        <div className="form-group">
                            <label>ایمیل</label>
                            <input
                                type="email"
                                value={data.email}
                                onChange={e => setData('email', e.target.value)}
                                className="form-control"
                                placeholder="admin@example.com"
                                autoFocus
                            />
                        </div>
                        
                        <div className="form-group">
                            <label>رمز عبور</label>
                            <input
                                type="password"
                                value={data.password}
                                onChange={e => setData('password', e.target.value)}
                                className="form-control"
                                placeholder="********"
                            />
                        </div>
                        
                        <div className="form-group checkbox-group">
                            <label className="checkbox">
                                <span>مرا به خاطر بسپار</span>
                                <input
                                    type="checkbox"
                                    checked={data.remember}
                                    onChange={e => setData('remember', e.target.checked)}
                                />
                            </label>
                        </div>
                        
                        <button type="submit" className="btn-login" disabled={processing}>
                            {processing ? 'در حال ورود...' : 'ورود به سیستم'}
                        </button>
                        
                        {canResetPassword && (
                            <div className="form-footer">
                                <Link href={route('password.request')}>رمز عبور را فراموش کرده‌اید؟</Link>
                            </div>
                        )}
                    </form>
                </div>
                
                <div className="login-right">
                    <div className="equipment-showcase">
                        <h3 className="animated-title">
                            <span>سامانه مدیریت بازدید</span>
                            <span>تجهیزات اتوماسیون</span>
                        </h3>
                    </div>
                </div>
            </div>
            
            <div className="company-footer">
                شرکت توزیع نیروی برق استان یزد | نسخه 2.0
            </div>
        </div>
    );
}
